### ISSUE TITLE
Failed to install on Rhel 7.3 - Unable to find image 'daocloud.io/golang:wheezy' locally

### ISSUE THREAD

**Issue by Chenjp** [leancloud/satori#10]
Dear,
    I got a message blow, could you help me?
:: Preparing docker images
:: - Copy alarm to build dir
:: - Copy frontend to build dir
:: - Build golang executables
Unable to find image 'daocloud.io/golang:wheezy' locally
docker: Error response from daemon: Get https://daocloud.io/v1/_ping: dial tcp: lookup daocloud.io on [::1]:53: read udp [::1]:43387->[::1]:53: read: connection refused.
See 'docker run --help'.

**Comment by feisuzhu** [comment]
It seems that your DNS is broken(daocloud.io resolved to loopback address).
Try `dig daocloud.io` on your shell and see if dig returns correct result.

**Comment by Chenjp** [comment]
Proxy setting lost because of account switch. After i setup proxy under the active account, different message received:
:: Preparing docker images
:: - Copy alarm to build dir
:: - Copy frontend to build dir
:: - Build golang executables
Unable to find image 'daocloud.io/golang:wheezy' locally
docker: Error response from daemon: Get https://daocloud.io/v1/_ping: dial tcp 106.75.86.139:443: getsockopt: no route to host.
See 'docker run --help'.


curl https://daocloud.io
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.11.6</center>
</body>
</html>

**Comment by feisuzhu** [comment]
Docker images are pulled by the docker daemon, not the command line tool.
Your proxy setting must affect docker daemon too.

See this link for further information:
http://stackoverflow.com/questions/23111631/cannot-download-docker-images-behind-a-proxy
