### ISSUE TITLE
Riemann 增加占比统计

### ISSUE THREAD

**Issue by Donghui0** [leancloud/satori#20]
- 问题描述
汇报metric 是关于 Nginx response time 相关. 按照时间区间从100ms 以下 到 10s 以上 分为9组. 如: lt.100ms,   100ms-300ms,  300ms-500ms, 500ms-800ms, .......
我希望能够获取最近5分钟平均每分钟当响应时间在1s 以上的请求量占当前请求总量的5% 的时候报警.
希望函数可动态传入多值: 
    如: perct("1s.3s", "3s.5s", "5s-8s")   则计算 1s-8s 的所有请求占用总请求比例.

3ks

**Comment by feisuzhu** [comment]
`riemann.folds` 里面有个 `sorted-sample` 可以了解下……
