### ISSUE TITLE
install时error，请问怎么解决？

### ISSUE THREAD

**Issue by pandakll** [leancloud/satori#27]
Installing collected packages: pip, six, pyparsing, packaging, appdirs, setuptools, wheel
  Found existing installation: six 1.8.0
    Uninstalling six-1.8.0:
Exception:
Traceback (most recent call last):
  File "/tmp/tmpdVDOcH/pip.zip/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/tmp/tmpdVDOcH/pip.zip/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/tmp/tmpdVDOcH/pip.zip/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/tmp/tmpdVDOcH/pip.zip/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/tmp/tmpdVDOcH/pip.zip/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/tmp/tmpdVDOcH/pip.zip/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/usr/lib/python2.7/shutil.py", line 300, in move
    rmtree(src)
  File "/usr/lib/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/usr/lib/python2.7/dist-packages/six-1.8.0.egg-info'
ERROR: Service 'alarm' failed to build: The command '/bin/sh -c python /alarm/get-pip.py' returned a non-zero code: 2

**Comment by feisuzhu** [comment]
抱歉，这个问题已经修了但是没 push 上来，已经 push 了。
更新下再试试看。
可以了的话就把 issue 关掉吧。

**Comment by pandakll** [comment]
还是这个错误问题

**Comment by feisuzhu** [comment]
`cat /etc/issue` 和 `sudo docker info` 的输出能贴一下么

**Comment by pandakll** [comment]
hi，如下：
1、 cat /etc/issue
\S
Kernel \r on an \m
2、sudo docker info
Containers: 12
 Running: 0
 Paused: 0
 Stopped: 12
Images: 33
Server Version: 17.05.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-327.13.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.51GiB
Name: bi-zhanjie-2.novalocal
ID: 3RLT:X5MZ:RL47:32BB:ACBC:KVYG:SIOS:TGNP:RU27:6GZC:UW54:NCRX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: overlay: the backing xfs filesystem is formatted without d_type support, which leads to incorrect behavior.
         Reformat the filesystem with ftype=1 to enable d_type support.
         Running without d_type support will not be supported in future releases.
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

**Comment by feisuzhu** [comment]
重现了，是 docker 的坑，还在看

**Comment by feisuzhu** [comment]
```
WARNING: overlay: the backing xfs filesystem is formatted without d_type support, which leads to incorrect behavior.
Reformat the filesystem with ftype=1 to enable d_type support.
Running without d_type support will not be supported in future releases.
```

是这个问题。
你的文件系统是 xfs 的，没开启 ftype=1，要重新加这个参数格式化。
或者换成 ext4 也行。
或者换成 zfs 直接用 zfs 的 storage backend，不要用 overlay 了。
