### ISSUE TITLE
git fetch 在網路很差的時候會卡住。造成「自動更新」的功能會被卡住，無法執行。

### ISSUE THREAD

**Issue by humorless** [leancloud/satori#28]
在這一行https://github.com/leancloud/satori/blob/9ce244c9d8e14d2d0c57fc3f6ca6f6f70e8de426/agent/plugins/update.go#L107

建議加上 timeout ，改成如  cmd := exec.Command("timeout", "60s", "git", "fetch")

參考資料： http://git.661346.n2.nabble.com/Request-timeout-option-for-remote-operations-esp-quot-git-fetch-quot-td7598943.html

**Comment by feisuzhu** [comment]
感谢报告 bug~

**Comment by feisuzhu** [comment]
fixed
