### ISSUE TITLE
influxdb的高可用是怎么做的？

### ISSUE THREAD

**Issue by hackstoic** [leancloud/satori#31]
存储用了influxdb， 用的是开源的版本，还是商业版本， 如果是开源版本， 请问高可用这块是怎么做的？

**Comment by feisuzhu** [comment]
没做高可用……
InfluxDB 官方提供的高可用也挺搓的，就没管它。

可以通过FS层或者RAID层做磁盘上的高可用，暂时没有更好的办法。

我们这边都是用的云，VM底层的磁盘肯定会做高可用的，所以没关心这个问题。
