### ISSUE TITLE
安装 satori 中需要检测 git 是否配置过 author 信息

### ISSUE THREAD

**Issue by skyworker0725** [leancloud/satori#40]
下面的问题是由于什么配置不对，请大神们帮忙确认一下：
Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'testuser@testserver1.(none)')

**Comment by feisuzhu** [comment]
```
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
```

按照这两个先配置一下……
