### ISSUE TITLE
DC/OS你们支持吗？ 其中的MESOS如何做？

### ISSUE THREAD

**Issue by binghun0518** [leancloud/satori#55]
您好，DC/OS你们支持吗？

**Comment by feisuzhu** [comment]
请问下你们是希望怎么用，这里支持是希望有哪些功能？

**Comment by feisuzhu** [comment]
我们有一些 Marathon 和 Mesos 的监控，但是跟我们的业务绑的比较紧

**Comment by binghun0518** [comment]
我现在是DC/OS这个控件，脚本里的IP list跟您变动很大。
好多取不到，就看到这些内容了。

**Comment by feisuzhu** [comment]
如果是这样的话建议自己修改一下插件，框架都有就是改一下 API 还是比较容易的。

DC/OS 我没有用过，也没法帮你写了，抱歉。
